#pragma once

#include <string>
#include <vector>

namespace arma3 {

struct ShaderInfo {
    const char* name;
    const char* description;
};

struct MaterialType {
    const char* name;
    const char* vertexShader;
    const char* pixelShader;
};

inline const std::vector<ShaderInfo>& pixelShaders() {
    static const std::vector<ShaderInfo> list = {
        {"Normal", "diffuse color modulate, alpha replicate"},
        {"NormalDXTA", "diffuse color modulate, alpha replicate, DXT alpha correction"},
        {"NormalMap", "normal map shader"},
        {"NormalMapThrough", "normal map shader - through lighting"},
        {"NormalMapGrass", "normal map shader - through lighting"},
        {"NormalMapDiffuse", ""},
        {"Detail", "detail texturing"},
        {"Interpolation", ""},
        {"Water", "sea water"},
        {"WaterSimple", "small water"},
        {"White", ""},
        {"WhiteAlpha", ""},
        {"AlphaShadow", "shadow alpha write"},
        {"AlphaNoShadow", "shadow alpha (no shadow write"},
        {"Dummy0", ""},
        {"DetailMacroAS", "detail with ambient shadow texture"},
        {"NormalMapMacroAS", "normal map with ambient shadow texture"},
        {"NormalMapDiffuseMacroAS", "diffuse normal map with ambient shadow texture"},
        {"NormalMapSpecularMap", "normal map with specular map"},
        {"NormalMapDetailSpecularMap", "normal map with detail and specular map"},
        {"NormalMapMacroASSpecularMap", "normal map with ambient shadow and specular map"},
        {"NormalMapDetailMacroASSpecularMap", "normal map with detail and ambient shadow and specular map"},
        {"NormalMapSpecularDIMap", "normal map with specular map, diffuse is inverse of specular"},
        {"NormalMapDetailSpecularDIMap", "normal map with detail and specular map, diffuse is inverse of specular"},
        {"NormalMapMacroASSpecularDIMap", "normal map with ambient shadow and specular map, diffuse is inverse of specular"},
        {"NormalMapDetailMacroASSpecularDIMap", "normal map with detail and ambient shadow and specular map, diffuse is inverse of specular"},
        {"Terrain1", "terrain - X layers"},
        {"Terrain2", "terrain - X layers"},
        {"Terrain3", "terrain - X layers"},
        {"Terrain4", "terrain - X layers"},
        {"Terrain5", "terrain - X layers"},
        {"Terrain6", "terrain - X layers"},
        {"Terrain7", "terrain - X layers"},
        {"Terrain8", "terrain - X layers"},
        {"Terrain9", "terrain - X layers"},
        {"Terrain10", "terrain - X layers"},
        {"Terrain11", "terrain - X layers"},
        {"Terrain12", "terrain - X layers"},
        {"Terrain13", "terrain - X layers"},
        {"Terrain14", "terrain - X layers"},
        {"Terrain15", "terrain - X layers"},
        {"TerrainSimple1", "terrainSimple - X layers"},
        {"TerrainSimple2", "terrainSimple - X layers"},
        {"TerrainSimple3", "terrainSimple - X layers"},
        {"TerrainSimple4", "terrainSimple - X layers"},
        {"TerrainSimple5", "terrainSimple - X layers"},
        {"TerrainSimple6", "terrainSimple - X layers"},
        {"TerrainSimple7", "terrainSimple - X layers"},
        {"TerrainSimple8", "terrainSimple - X layers"},
        {"TerrainSimple9", "terrainSimple - X layers"},
        {"TerrainSimple10", "terrainSimple - X layers"},
        {"TerrainSimple11", "terrainSimple - X layers"},
        {"TerrainSimple12", "terrainSimple - X layers"},
        {"TerrainSimple13", "terrainSimple - X layers"},
        {"TerrainSimple14", "terrainSimple - X layers"},
        {"TerrainSimple15", "terrainSimple - X layers"},
        {"Glass", "glass shader with environmental map"},
        {"NonTL", "very simple 2D pixel shader"},
        {"NormalMapSpecularThrough", "normal map shader - through with specular lighting"},
        {"Grass", "grass shader - alpha discretized"},
        {"NormalMapThroughSimple", "simple version of NormalMapThrough shader"},
        {"NormalMapSpecularThroughSimple", "simple version of NormalMapSpecularThrough shader"},
        {"Road", "road shader"},
        {"Shore", "shore shader"},
        {"ShoreWet", "shore shader for the wet part"},
        {"Road2Pass", "road shader - second pass"},
        {"ShoreFoam", "shore shader for the foam on the top of the shore"},
        {"NonTLFlare", "shader to be used for flares"},
        {"NormalMapThroughLowEnd", "substitute shader for NormalMapThrough shaders for low-end settings"},
        {"TerrainGrass1", "terrain grass - X layers"},
        {"TerrainGrass2", "terrain grass - X layers"},
        {"TerrainGrass3", "terrain grass - X layers"},
        {"TerrainGrass4", "terrain grass - X layers"},
        {"TerrainGrass5", "terrain grass - X layers"},
        {"TerrainGrass6", "terrain grass - X layers"},
        {"TerrainGrass7", "terrain grass - X layers"},
        {"TerrainGrass8", "terrain grass - X layers"},
        {"TerrainGrass9", "terrain grass - X layers"},
        {"TerrainGrass10", "terrain grass - X layers"},
        {"TerrainGrass11", "terrain grass - X layers"},
        {"TerrainGrass12", "terrain grass - X layers"},
        {"TerrainGrass13", "terrain grass - X layers"},
        {"TerrainGrass14", "terrain grass - X layers"},
        {"TerrainGrass15", "terrain grass - X layers"},
        {"Crater1", "Crater rendering - X craters"},
        {"Crater2", "Crater rendering - X craters"},
        {"Crater3", "Crater rendering - X craters"},
        {"Crater4", "Crater rendering - X craters"},
        {"Crater5", "Crater rendering - X craters"},
        {"Crater6", "Crater rendering - X craters"},
        {"Crater7", "Crater rendering - X craters"},
        {"Crater8", "Crater rendering - X craters"},
        {"Crater9", "Crater rendering - X craters"},
        {"Crater10", "Crater rendering - X craters"},
        {"Crater11", "Crater rendering - X craters"},
        {"Crater12", "Crater rendering - X craters"},
        {"Crater13", "Crater rendering - X craters"},
        {"Crater14", "Crater rendering - X craters"},
        {"Sprite", "Shader used for sprite rendering - it uses SoftParticle approach"},
        {"SpriteSimple", "Shader used for sprite rendering - no SoftParticle approach"},
        {"Cloud", "Shader used for clouds"},
        {"Horizon", "Shader used for the horizon"},
        {"Super", "Super shader"},
        {"Multi", "Multi shader"},
        {"TerrainX", "terrain - general number of layers"},
        {"TerrainSimpleX", "terrainSimple - general number of layers"},
        {"TerrainGrassX", "terrain grass - general number of layers"},
        {"Tree", "Tree shader"},
        {"TreePRT", "Tree shader - very cheap shader with PRT"},
        {"TreeSimple", "Tree shader - simpler version of Tree"},
        {"Skin", "Human skin - derived from Super shader"},
        {"CalmWater", "calm water surface"},
        {"TreeAToC", "tree with alpha to coverage"},
        {"GrassAToC", "grass with alpha to coverage"},
        {"TreeAdv", "advanced tree crown shader"},
        {"TreeAdvSimple", "advanced tree crown shader"},
        {"TreeAdvTrunk", "advanced tree shader"},
        {"TreeAdvTrunkSimple", "advanced tree shader"},
        {"TreeAdvAToC", "advanced tree crown shader"},
        {"TreeAdvSimpleAToC", "advanced tree crown shader"},
        {"TreeSN", "Tree shader width simple noise"},
        {"SpriteExtTi", "Sprite used for vehicles covering"},
        {"TerrainSNX", "terrain - general number of layers + satellite normal map"},
        {"InterpolationAlpha", ""},
        {"VolCloud", "Shader used for volumetric cloud - it uses SoftParticle approach"},
        {"VolCloudSimple", "Shader used for volumetric cloud - no SoftParticle approach"},
        {"UnderwaterOcclusion", "Shader used for underwater occlusion object"},
        {"SimulWeatherClouds", "SimulWeather clouds"},
        {"SimulWeatherCloudsWithLightning", "SimulWeather clouds with lightning"},
        {"SimulWeatherCloudsCPU", "SimulWeather clouds with CPU distance fading"},
        {"SimulWeatherCloudsWithLightningCPU", "SimulWeather clouds with lightning and CPU distance fading"},
        {"SuperExt", "skyscraper & building, intended as super shader light version"},
        {"SuperHair", "super shader for hair rendering"},
        {"SuperHairAtoC", "super shader for hair rendering, atoc version"},
        {"Caustics", "shader for caustics effect"},
        {"Refract", "shader for refractions _ARMA3_REFRACTION"},
        {"SpriteRefract", "_ARMA3_REFRACTION_SPRITES - Shader used for sprite rendering with refraction - it uses Sof"},
        {"SpriteRefractSimple", "_ARMA3_REFRACTION_SPRITES - Shader used for sprite rendering with refraction- no SoftParti"},
        {"SuperAToC", "Super shader AToC variant"},
        {"NonTLFlareNew", "shader to be used for flares, new HDR version"},
        {"NonTLFlareLight", "shader to be used for flares from dynamic lights (not sun)"},
        {"TerrainNoDetailX", "terrainX without detail map"},
        {"TerrainNoDetailSNX", "terrainSNX without detail map"},
        {"TerrainSimpleSNX", "terrainSNX without parallax mapping"},
        {"NormalPiP", "shader for PiP screens"},
        {"NonTLFlareNewNoOcclusion", "same as NonTLFlareNew, but without occlusion test"},
        {"Empty", "empty shader, does not output anything (used only for depth output)"},
        {"Point", "Shader used for point lights"},
        {"TreeAdvTrans", "same as TreeAdv, but there is translucency map in alpha channel of MCA texture ( instead o"},
        {"TreeAdvTransAToC", "same as TreeAdv, but there is translucency map in alpha channel of MCA texture ( instead o"},
        {"Collimator", "special shader for collimator"},
        {"LODDiag", "shader for lod diagnostics"},
        {"DepthOnly", "Special replacement for AlphaOnly for priming non- alpha objects"},
    };
    return list;
}

inline const std::vector<ShaderInfo>& vertexShaders() {
    static const std::vector<ShaderInfo> list = {
        {"Basic", "N/A"},
        {"NormalMap", "normal map"},
        {"NormalMapDiffuse", "normal map + detail map"},
        {"Grass", ""},
        {"Dummy1", ""},
        {"Dummy2", ""},
        {"ShadowVolume", "shadow volumes"},
        {"Water", "per-vertex water animation"},
        {"WaterSimple", "per-vertex water animation (without foam)"},
        {"Sprite", "particle effects"},
        {"Point", "anti-aliased points"},
        {"NormalMapThrough", "normal map - tree shader"},
        {"Dummy3", ""},
        {"Terrain", "one pass terrain, no alpha mask - based on VSNormalMapDiffuse"},
        {"BasicAS", "ambient shadow"},
        {"NormalMapAS", "normal map with ambient shadow"},
        {"NormalMapDiffuseAS", "diffuse normal map with ambient shadow Glass /*glass shader*/ \\"},
        {"NormalMapSpecularThrough", "normal map with specular - tree shader"},
        {"NormalMapThroughNoFade", "normal map - tree shader - without face fading"},
        {"NormalMapSpecularThroughNoFade", "normal map with specular - tree shader - without face fading"},
        {"Shore", "sea shore - similar to Terrain"},
        {"TerrainGrass", "grass layer - similar to Terrain"},
        {"Super", "Super shader - expensive shader containing all common features"},
        {"Multi", "Multi shader - shader with multiple layers suitable for huge surfaces like houses"},
        {"Tree", "Tree shader - cheap shader designed for trees and bushes"},
        {"TreeNoFade", "Tree shader - cheap shader designed for trees and bushes - without face fading"},
        {"TreePRT", "Tree shader - very cheap shader designed for trees and bushes"},
        {"TreePRTNoFade", "Tree shader - very cheap shader designed for trees and bushes - without face fading"},
        {"Skin", "Human skin - derived from Super shader"},
        {"CalmWater", "calm water surface - special shader"},
        {"TreeAdv", "advanced tree crown shader VSTreeAdv"},
        {"TreeAdvTrunk", "advanced tree crown shader VSTreeAdvTrunk"},
        {"VolCloud", "volumetric clouds"},
        {"Road", "roads"},
        {"UnderwaterOcclusion", "underwater occlusion object vertex shader"},
        {"SimulWeatherClouds", "simul weather clouds"},
        {"SimulWeatherCloudsCPU", "simul weather clouds with CPU distance fading"},
        {"SpriteOnSurface", "sprite on surface"},
        {"TreeAdvModNormals", "advanced tree crown shader with modified vertex normals"},
        {"Refract", "vertex shader for refractions - _ARMA3_REFRACTION"},
        {"SimulWeatherCloudsGS", "simul weather clouds with geom shader"},
        {"BasicFade", "basic with face fading (based on the angle with camera direction"},
        {"Star", "Similar to Point but only for drawing stars"},
        {"TreeAdvNoFade", "advanced tree crown shader - no face fading"},
    };
    return list;
}

inline const std::vector<MaterialType>& materialTypes() {
    static const std::vector<MaterialType> list = {
        {"General material", "Basic", "Normal"},
        {"DXTA material", "Basic", "NormalDXTA"},
        {"Basic detail map", "Basic", "Detail"},
        {"", "Basic", "White"},
        {"", "Basic", "WhiteAlpha"},
        {"Basic glass", "Basic", "AlphaShadow"},
        {"Normal map", "NormalMap", "NormalMap"},
        {"Normal map HQ specular", "NormalMap", "NormalMapSpecularMap"},
        {"", "NormalMap", "NormalMapSpecularDIMap"},
        {"Normal map HQ detail map specular", "NormalMap", "NormalMapDetailSpecularMap"},
        {"", "NormalMap", "NormalMapDetailSpecularDIMap"},
        {"Basic normal detail", "NormalMapDiffuse", "NormalMapDiffuse"},
        {"", "Water", "Water"},
        {"Water simple", "WaterSimple", "WaterSimple"},
        {"", "NormalMapThrough", "NormalMapThrough"},
        {"", "NormalMapThrough", "NormalMapThroughSimple"},
        {"Basic Tree crown", "NormalMapSpecularThrough", "NormalMapSpecularThrough"},
        {"", "NormalMapSpecularThrough", "NormalMapSpecularThroughSimple"},
        {"", "NormalMapThroughNoFade", "NormalMapThrough"},
        {"", "NormalMapThroughNoFade", "NormalMapThroughSimple"},
        {"", "NormalMapSpecularThroughNoFade", "NormalMapSpecularThrough"},
        {"", "NormalMapSpecularThroughNoFade", "NormalMapSpecularThroughSimple"},
        {"Detail macro AS", "BasicAS", "DetailMacroAS"},
        {"Normal map macro AS", "NormalMapAS", "NormalMapMacroAS"},
        {"Normal map HQ specular macro AS", "NormalMapAS", "NormalMapMacroASSpecularMap"},
        {"", "NormalMapAS", "NormalMapMacroASSpecularDIMap"},
        {"Normal map HQ detail specular macro AS", "NormalMapAS", "NormalMapDetailMacroASSpecularMap"},
        {"", "NormalMapAS", "NormalMapDetailMacroASSpecularDIMap"},
        {"Normal map detail macro AS", "NormalMapDiffuseAS", "NormalMapDiffuseMacroAS"},
        {"Basic glass reflectance", "Glass", "Glass"},
        {"Antiwater", "Basic", "AlphaNoShadow"},
        {"Super_shader", "Super", "Super"},
        {"Multimaterial", "Multi", "Multi"},
        {"Tree", "Tree", "TreeNoFade"},
        {"TreePRT", "TreePRT", "TreePRT"},
    };
    return list;
}

} // namespace arma3
